### ISSUE TITLE
Fail to run and then fail to produce plasmids and test data[Bug]: 

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [epi2me-labs/wf-clone-validation#10]
### What happened?

I really struggled getting this running (docker and singularity failed). Also conda installs didn't work. At the end I got mamba install working with a fixed_conda environment. 

Now it runs but doesn't produce plasmid sequences even with 

nextflow run epi2me-labs/wf-clone-validation -profile fixed_conda --fastq test_data/test --db_directory XXX -c XXX --no_reconcil.

If finishes and produces a report but does not generate plasmid consensus sequences.

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - EPI2ME Labs Versions

v0.2.4

### Workflow Execution - Execution Profile

Conda

### Workflow Version

v0.2.4

### Relevant log output

```shell
Aug.-26 06:52:21.978 [Task monitor] INFO  nextflow.processor.TaskProcessor - [c6/952e62] NOTE: Process `pipeline:assembleCore (1)` terminated with an error exit status (1) -- Execution is retried (4)

Not sure where to find the log file for the actual command run.
```

**Comment by sarahjeeeze** [comment]
Hi, usually there should be some clues in the wf-clone-validation-report.html as to why the assembly failed. What is average read quality and length? You may also need to adjust the approx_size and assm_coverage parameters to better fit your data. What were the error messages for docker and singularity failing?

**Comment by sarahjeeeze** [comment]
Closing through lack of response from original poster
