### ISSUE TITLE
can I add my own annotation file (genebank format) into the wf-clone-validation-db 

### ISSUE THREAD

**Issue by lzhangUT** [epi2me-labs/wf-clone-validation#19]
### What happened?

Hi, 
I am running wf-clone-validation workflow, and it worked out fine.
I wonder if I have my own annotation file (in genebank format), can I add it into the wf-clone-validation-db folder and use it to get the corresponding result in the feature table? If not, how can I add external/my own annotation file into the workflow and what formats the workflow can take?
Thank you in advance for your help

### Operating System

ubuntu 18.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

THE LATEST

### Relevant log output

```shell
Na
```

**Comment by sarahjeeeze** [comment]
Hi, technically you can but I need to verify the database format required. We will consider putting together some instructions about how to do this in the future.

**Comment by sarahjeeeze** [comment]
Hi, we won't be adding these in the near future so closing for now. But we will try to add this at some point thanks for the feedback.
