### ISSUE TITLE
[Enhancement] combine sample and size sheets

### ISSUE THREAD

**Issue by JWDebler** [epi2me-labs/wf-clone-validation#22]
### What happened?

It would be great to just supply a single file that contains the sample names (per barcode) and approximate sizes, since the pipeline combines the two anyways. Fewer manually created input files lead to fewer accidental errors. 

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

latest

### Relevant log output

```shell
none
```

**Comment by sarahjeeeze** [comment]
Hi, Thanks again for your feedback, we have now done this - they are combined in the sample sheet.

**Comment by sarahjeeeze** [comment]
Closing as this is now updated.
