### ISSUE TITLE
[Bug]:   README does not include expected outcome from test_data

### ISSUE THREAD

**Issue by ChristopherRichie** [epi2me-labs/wf-clone-validation#23]
### What happened?

A bug happened!

If I run the the "typical pipeline command" on the provided test_data, using the parameters included in the --help file, 
I get a result, but I do not know if the result I obtained is appropriate.  

the test_data folder has subfolders for barcodes 01-04... but the report on my "typical result" includes information on only barcodes 01-03.  Moreover, the report says that barcode01 passed, but 02, 03 failed due to insufficient reads.

Would you please append the readme or test_data folder to include an appropriate "correct" report, for use as comparison with someone running the test locally?

thanks

### Operating System

ubuntu 18.04

### Workflow Execution

Command line

### Workflow Execution - EPI2ME Labs Versions

NIH HPC Biowulf, running nextflow and singularity with --cpus-per-task=14 --mem=16g --gres=lscratch:400,gpu:v100:1

### Workflow Execution - CLI Execution Profile

Singularity

### Workflow Version

 wf-clone-validation v0.3.1-g97e1eab

### Relevant log output

```shell
--------------------------------------------------------------------------------
This is epi2me-labs/wf-clone-validation v0.3.1-g97e1eab.
--------------------------------------------------------------------------------
Checking fastq input.
executor >  slurm (24)
[ae/ee97d8] process > fastcat (2)                       [100%] 3 of 3 ✔
[76/8ce96b] process > pipeline:checkIfEnoughReads (3)   [100%] 3 of 3 ✔
[ae/49ac7c] process > pipeline:assembleCore (1)         [100%] 1 of 1 ✔
[3b/483661] process > pipeline:lookup_medaka_model (1)  [100%] 1 of 1 ✔
[e6/05c2f7] process > pipeline:medakaPolishAssembly (1) [100%] 1 of 1 ✔
[52/a0520d] process > pipeline:downsampledStats (1)     [100%] 1 of 1 ✔
[e5/ee64a5] process > pipeline:findPrimers (1)          [100%] 1 of 1 ✔
[16/224e93] process > pipeline:medakaVersion            [100%] 1 of 1 ✔
[83/1f85c9] process > pipeline:getVersions              [100%] 1 of 1 ✔
[b7/6c8fc4] process > pipeline:getParams                [100%] 1 of 1 ✔
[10/1be647] process > pipeline:runPlannotate (1)        [100%] 1 of 1 ✔
[96/12db9f] process > pipeline:inserts                  [100%] 1 of 1 ✔
[de/cf1b63] process > pipeline:report (1)               [100%] 1 of 1 ✔
[85/334b70] process > output (7)                        [100%] 7 of 7 ✔
Completed at: 07-Jul-2023 10:26:31
Duration    : 22m 5s
CPU hours   : 0.1
Succeeded   : 24
```

**Comment by sarahjeeeze** [comment]
Hi, I can confirm those results are expected. We will consider adding an example report in the future, in the meantime running the demo data set in the EPI2ME Labs application can be used to see the expected results.

**Comment by sarahjeeeze** [comment]
Closing through lack of response.
