### ISSUE TITLE
Failed to combine FastQ error

### ISSUE THREAD

**Issue by Vijibt** [epi2me-labs/wf-clone-validation#3]
Hi,
I am trying to run clone-validation using basic parameters on my mac but I am getting error with exit status 127 as below:
Checking sample sheet.
executor >  local (4)
executor >  local (4)
[8f/a1ba70] process > checkSampleSheet (1)          [100%] 1 of 1 ✔
[9b/98be97] process > pipeline:combineFastq (1)     [  0%] 0 of 1
[-        ] process > pipeline:filterHostReads      -
[-        ] process > pipeline:assembleCore         -
[-        ] process > pipeline:medakaPolishAssembly -
[-        ] process > pipeline:downsampledStats     -
[-        ] process > pipeline:assemblyMafs         -
[-        ] process > pipeline:findPrimers          -
[51/b580c4] process > pipeline:getVersions          [  0%] 0 of 1
executor >  local (4)
[8f/a1ba70] process > checkSampleSheet (1)          [100%] 1 of 1 ✔
[9b/98be97] process > pipeline:combineFastq (1)     [100%] 1 of 1, failed: 1 ✔
[-        ] process > pipeline:filterHostReads      -
[-        ] process > pipeline:assembleCore         -
executor >  local (4)
[8f/a1ba70] process > checkSampleSheet (1)          [100%] 1 of 1 ✔
[9b/98be97] process > pipeline:combineFastq (1)     [100%] 1 of 1, failed: 1 ✔
[-        ] process > pipeline:filterHostReads      -
[-        ] process > pipeline:assembleCore         -
executor >  local (4)
[8f/a1ba70] process > checkSampleSheet (1)          [100%] 1 of 1 ✔
[9b/98be97] process > pipeline:combineFastq (1)     [100%] 1 of 1, failed: 1 ✔
[-        ] process > pipeline:filterHostReads      -
[-        ] process > pipeline:assembleCore         -
executor >  local (4)
[8f/a1ba70] process > checkSampleSheet (1)          [100%] 1 of 1 ✔
[9b/98be97] process > pipeline:combineFastq (1)     [100%] 1 of 1, failed: 1 ✔
[-        ] process > pipeline:filterHostReads      -
[-        ] process > pipeline:assembleCore         -
[-        ] process > pipeline:medakaPolishAssembly -
[-        ] process > pipeline:downsampledStats     -
[-        ] process > pipeline:assemblyMafs         -
[-        ] process > pipeline:findPrimers          -
[51/b580c4] process > pipeline:getVersions          [100%] 1 of 1 ✔
[ae/44ff1d] process > pipeline:getParams            [100%] 1 of 1 ✔
[-        ] process > pipeline:report               -
[-        ] process > output                        -
Checking input directory structure.
 - Found fastq files, assuming single sample
WARN: Task runtime metrics are not reported when using macOS without a container engine
[9b/98be97] NOTE: Process `pipeline:combineFastq (1)` terminated with an error exit status (127) -- Error is ignored
WARN: Cannot serialize context map. Cause: java.lang.IllegalArgumentException: Unable to create serializer "com.esotericsoftware.kryo.serializers.FieldSerializer" for class: jdk.internal.reflect.DelegatingMethodAccessorImpl -- Resume will not work on this process

What could be the reason?
Thank you!

**Comment by sarahjeeeze** [comment]
Hi, would you be able to share the cmd you ran with us?

**Comment by Vijibt** [comment]
> Hi, would you be able to share the cmd you ran with us?

nextflow run epi2me-labs/wf-clone-validation --fastq /Users/vij/Desktop/Plasmids/RB02_EC --samples /Users/vij/Desktop/Plasmids/sample_sheet.txt --out_dir /Users/vij/Desktop/Plasmids/output2 --db_directory /Users/vij/Desktop/Plasmids/ --host_reference /Users/vij/Desktop/plasmids/genome.fasta -profile standard

**Comment by sarahjeeeze** [comment]
Thanks, I have been unable to recreate the error so far.  Do you know what version of Nextflow you are using and do you have docker set up?

**Comment by sarahjeeeze** [comment]
Also it may be worth updating your wf-version with `nextflow pull epi2me-labs/wf-clone-validation` as it looks like you are on an older one. Not that it should make a difference.

**Comment by Vijibt** [comment]
> Also it may be worth updating your wf-version with `nextflow pull epi2me-labs/wf-clone-validation` as it looks like you are on an older one. Not that it should make a difference.

Thanks. I ran the workflow after updating and this time I had issues with assemble_core as below:
executor >  local (18)
[5f/aab303] process > start_ping:pingMessage (1)    [100%] 1 of 1 ✔
[3e/d0ad92] process > pipeline:combineFastq (1)     [100%] 1 of 1 ✔
[ac/c04676] process > pipeline:filterHostReads (1)  [100%] 1 of 1 ✔
[de/be8920] process > pipeline:assembleCore (1)     [100%] 6 of 6, failed: 5,..
[-        ] process > pipeline:medakaPolishAssembly -
[c3/87ff89] process > pipeline:downsampledStats (1) [100%] 1 of 1 ✔
[-        ] process > pipeline:assemblyMafs         -
[-        ] process > pipeline:findPrimers          -
[ef/714b00] process > pipeline:getVersions          [100%] 1 of 1 ✔
[9e/3cd6af] process > pipeline:getParams            [100%] 1 of 1 ✔
[ef/3c095f] process > pipeline:report (1)           [100%] 1 of 1 ✔
[5c/5ff4f4] process > output (2)                    [100%] 4 of 4 ✔
[3f/c22766] process > end_ping:pingMessage          [100%] 1 of 1 ✔
[be/79d31c] NOTE: Process `pipeline:assembleCore (1)` terminated with an error exit status (1) -- Execution is retried (3)
[74/7c3629] NOTE: Process `pipeline:assembleCore (1)` terminated with an error exit status (1) -- Execution is retried (4)
[89/e9380b] NOTE: Process `pipeline:assembleCore (1)` terminated with an error exit status (1) -- Execution is retried (5)
WARN: Task runtime metrics are not reported when using macOS without a container engine

Completed at: 08-Dec-2021 18:51:39
Duration    : 7m 19s
CPU hours   : 0.1 (30.2% failed)
Succeeded   : 13
Failed      : 5

**Comment by Vijibt** [comment]
> Thanks, I have been unable to recreate the error so far. Do you know what version of Nextflow you are using and do you have docker set up?

It is N E X T F L O W  ~  version 21.10.4. Yes, I have docker set up.

**Comment by sarahjeeeze** [comment]
It looks like it has completed as expected but has failed to assemble which may be down to the sample. The wf-clone-validation-report.html in the output folder should be available and provide some clues as to why it may have failed? eg. low number of reads. You may be able to improve it by adjusting the advanced parameters based on your sample  `--approx_size --assm_coverage --trim_length` they are currently set at  `--approx_size 7000 --assm_coverage 60 --trim_length 150`

**Comment by Vijibt** [comment]
> It looks like it has completed as expected but has failed to assemble which may be down to the sample. The wf-clone-validation-report.html in the output folder should be available and provide some clues as to why it may have failed? eg. low number of reads.
> 
> You may be able to improve it by adjusting the advanced parameters based on your sample `--approx_size --assm_coverage --trim_length` they are currently set at `--approx_size 7000 --assm_coverage 60 --trim_length 150`

I can see the below reasons in wf-clone validation-report.html:

Sample | pass/failed reason | Length
-- | -- | --
RB02_EC_MAD7_2 | Failed to assemble using Canu | N/A

I will try to re-run with advanced parameters.
