### ISSUE TITLE
v0.5.2 Downsampled plots became slim

### ISSUE THREAD

**Issue by drabitoris** [epi2me-labs/wf-clone-validation#32]
### Ask away!

Hi team, 

Thanks for the updating!

I've just run the latest version v0.5.2 and it seems it has problem with the downsampled plots. (please see attached. Not sure if it's only me though) All the previous versions worked well to me. 

![Screenshot 2023-10-09 at 11 10 07 am](https://github.com/epi2me-labs/wf-clone-validation/assets/79437714/f03ebc21-5e35-45f2-abf6-74266f73c6eb)

**Comment by julibeg** [comment]
Hi @drabitoris!

Just to confirm: this only affects the plots in the "Downsampled" tab and the plots in "Raw" are fine?

**Comment by drabitoris** [comment]
Among the about 40 samples I just ran, all the 'downsampled' were slim and a few 'raw's in only one html report were slim. Thanks for your reply!

**Comment by gabyrech** [comment]
Same here, only first sample 'raw' looks normal, remaining 'downsampled' and 'raw' are slim.

**Comment by sarahjeeeze** [comment]
Thanks for this, we should have fixed this now in v0.5.3

**Comment by gabyrech** [comment]
Tried and look good now, thanks!
