### ISSUE TITLE
What is the rationale of using '--meta' parameter on Flye?

### ISSUE THREAD

**Issue by gabyrech** [epi2me-labs/wf-clone-validation#34]
### Ask away!

Hi! 
Since _--meta_  parameter in Flye is for metagenomics assemblies (a.k.a highly non-uniform coverage samples, and [wf-clone-validation](https://github.com/epi2me-labs/wf-clone-validation) is mostly thought to be used for homogenous coverage samples, wouldn't be better just to use Flye on 'regular' mode? 

Furthermore, I am thinking the _--meta_ parameter could probably be adding some additional noise in the next step (Trycycler reconciliation). During the reconciliation, there is one step that is recommended to be manual by Trycycler developers (inspect the clusters to decide which are valid), but in the pipeline you skip this manual step (understandable) and pick all clusters, which in the case of [wf-clone-validation](https://github.com/epi2me-labs/wf-clone-validation) are all three Flye assemblies reconstructed from the subsampled/subsetting reads. If any of these assemblies contains an underrepresented sequence (obtained because we used --meta) and because we dont do manual inspection before the reconciliation, this sequence will end up being incorporated in the consensus sequence, am I right?

How about making _--meta_ a parameter on [wf-clone-validation](https://github.com/epi2me-labs/wf-clone-validation) so users can decide whether tho use it or not?

Thank you!
Gabriel

**Comment by sarahjeeeze** [comment]
Hi, thank you for this useful feedback. I think we originally added it because it led to more robust results when running with some of our internal test data sets but I think you are right that it should be an optional parameter for users to select.

**Comment by sarahjeeeze** [comment]
Hi, we have now parameterised this in the latest version

**Comment by gabyrech** [comment]
Awesome! Thank you Sarah!

**Comment by sarahjeeeze** [comment]
Closing as this is resolved.
