### ISSUE TITLE
Workflow working, but no final fastq file or gbk file generated (medaka polishing failed)

### ISSUE THREAD

**Issue by MattCarlile05** [epi2me-labs/wf-clone-validation#38]
### Operating System

macOS

### Workflow Version

v0.3.1

### Workflow Execution

EPI2ME Desktop application

### EPI2ME Version

v5.0.2

### Workflow Execution - CLI Execution Profile

None

### What happened?

The assembly works fine but no final fastq file or gbk file generated.

I uploaded 4K reads, and used the default workflow parameters.
I’ve run the workflow using the Epi2me labs Desktop and the Command line, in both cases with Docker. The assemblies look fine and the html reports looks good.

This has happened every time I have run the workflow, the log on Epi2me doesn't highlight an error - its only when you look at the execution log report that the errors 'Failed due to insufficient reads' and 'Failed to polish assembly with Medaka' are indicated. 

### Relevant log output

```shell
STATUS="Failed due to insufficient reads"
    mv per-read-stats.tsv AcrB_pBAD.stats
    fastcat -s AcrB_pBAD -r AcrB_pBAD.interim -a 4500 -b 13500 input.fastq.gz     | bgzip -@ 3 > interim.fastq.gz
    if [[ "$(wc -l < "AcrB_pBAD.interim")" -ge "48" ]]; then
        mv interim.fastq.gz AcrB_pBAD.fastq.gz
        STATUS="Completed successfully"
    fi

STATUS="Failed to polish assembly with Medaka"
    medaka_consensus -i "AcrB_pBAD.downsampled.fastq" -d "AcrB_pBAD.reconciled.fasta" -m "r1041_e82_400bps_hac_g632
" -o . -t 4 -f
    echo ">AcrB_pBAD" >> "AcrB_pBAD.final.fasta"
    sed "2q;d" consensus.fasta >> "AcrB_pBAD.final.fasta"
    STATUS="Completed successfully"
```

**Comment by sarahjeeeze** [comment]
Hi, Thanks for letting us know. Could you share the `.nextflow.log` or the tar that is output if you click report issue in the app anyway?

**Comment by MattCarlile05** [comment]
[nextflow.log](https://github.com/epi2me-labs/wf-clone-validation/files/13920657/nextflow.log)

**Comment by sarahjeeeze** [comment]
Hi, does the final report html get output and are these errors reported there?

**Comment by sarahjeeeze** [comment]
For each of your plasmids is there a plannotate annotated assembly in the report? From the log it looks like the workflow completed as expected, where did you see the text that you've pasted in the relevant log output? Was there any other error message with that?

**Comment by MattCarlile05** [comment]
There is a pLannotate assembly for each plasmid in the report. The errors are in 'NextFlow Workflow Report' html file located in the outputs execution folder.

**Comment by sarahjeeeze** [comment]
oh would you be able to update the workflow to the latest version and let me know if it works? I noticed it says v0.3.1 - it may be an old bug.

**Comment by sarahjeeeze** [comment]
Closing through lack of response, please open a new issue if it persists with the latest version v1.1.0
