### ISSUE TITLE
failed to run commands

### ISSUE THREAD

**Issue by ryao-mdanderson** [epi2me-labs/wf-clone-validation#41]
### Ask away!

Dear author,

For some reasons, I could failed to 
 nextflow run epi2me-labs/wf-clone-validation –help

the error message is 
 ERROR ~ Validation of pipeline parameters failed!
-- Check '.nextflow.log' file for details
ERROR ~ * Missing required parameter: --fastq
-- Check '.nextflow.log' file for details

I also tried running with demo data, I hit an error :
ERROR ~ Error executing process > 'pipeline:medakaVersion'
 Caused by:
  Failed to pull singularity image
  command: singularity pull  --name ontresearch-medaka-sha61a9438d745a78030738352e084445a2db3daa2a.img.pulling.1710195000442 docker://ontresearch/medaka:sha61a9438d745a78030738352e084445a2db3daa2a > /dev/null
  status : 255
  ...
 FATAL:   While making image from oci registry: error fetching image to cache: while building SIF from layers: conveyor failed to get: no descriptor found for reference "3290aa3a218b2b5b4e77cfeb367d91827f32ea827cc90219e723b00a6fb6f490"
 issue report to github

Please advise if I overlooked anything.

Thank you,
Rong Yao

**Comment by cjw85** [comment]
Please reopen your issue using the appropriate issue template. Providing the requested information really helps us to help you.

**Comment by ryao-mdanderson** [comment]
[nextflow.log](https://github.com/epi2me-labs/wf-clone-validation/files/14565149/nextflow.log)
Attached .nextflow.log
