### ISSUE TITLE
How to update workflow for Dorado basecalling output

### ISSUE THREAD

**Issue by rwiltonanl** [epi2me-labs/wf-clone-validation#43]
### Ask away!

Hello,

I got an "project version outdated" message (bottom) when I ran wf-clone-validation today.  Can you please provide or direct me to directions on how to update this?  I'm not sure what file/directory it is referring to.  I am running this on a linux system, and I am using Singularity (I can't use Docker on my system).

Also, although I was able to run the workflow with the outdated version, and it seemed to produce good results, I initially had some trouble getting this to work with Dorado output.  I discovered I had to organize the fastqs in directories with barcode names, similar to how the Guppy output was set up.  Does that sound right?  I didn't see any notes about any changes regarding Dorado basecalling.  ( - -Perhaps if I could get that project version updated, this would be a moot point:)  )

N E X T F L O W  ~  version 23.10.1
NOTE: Your local project version looks outdated - a different revision is available in the remote repository [2c04b9d884]
Launching `https://github.com/epi2me-labs/wf-clone-validation` [kickass_newton] DSL2 - revision: fb10581c66 [master]

Thanks for your help!

**Comment by SamStudio8** [comment]
@rwiltonanl You can run `nextflow pull epi2me-labs/wf-clone-validation` to update the workflow (if you wish to). You may want to have a look at the CHANGELOG to see what changes may impact you https://github.com/epi2me-labs/wf-clone-validation/blob/master/CHANGELOG.md before updating.

**Comment by rwiltonanl** [comment]
Thanks so much!  I'll definitely try this.  I'm happy to see canu as an alternative assembler.  Sometimes I get multimeric plasmids with flye, even if I filter out longer reads, so it will be great to have a different assembler to try.

**Comment by mattdmem** [comment]
Closing this as it looks like your question has been answered @rwiltonanl. Please do open another question if you need further information.
