### ISSUE TITLE
workflow in HPC cluster

### ISSUE THREAD

**Issue by mbacino** [epi2me-labs/wf-clone-validation#44]
### Ask away!

I do not have super user privileges on my HPC cluster and therefore cannot run a rooted version of docker. Is there a way around this so that I can run this workflow on the HPC? Can this work flow supported by a rootless version of docker? Thanks!

**Comment by sarahjeeeze** [comment]
Hey, we don't currently have support for the rootless version. The other option which we do support is singularity which overcomes the privileges issue. https://labs.epi2me.io/singularity/

**Comment by sarahjeeeze** [comment]
Closing through lack of response
