### ISSUE TITLE
Inconsistant raw read count along the report

### ISSUE THREAD

**Issue by drabitoris** [epi2me-labs/wf-clone-validation#51]
### Ask away!

Hi team,
Thank you so much for the lastest update v1.3.0! 

I've just tested (with the newly added 'full reference' option) and noticed a little inconsistency of the "raw read count" along the report. 

Please see attached the screenshot of the raw read counts of the same sample TW4 that are different top (histogram) and bottom (raw read count in "Read stats").
![Screenshot 2024-06-26 at 10 53 38 am](https://github.com/epi2me-labs/wf-clone-validation/assets/79437714/893c8cdd-1261-4b6d-a794-7b424a374534)

Cheers,
Layla

**Comment by julibeg** [comment]
Hi Layla, thanks for bringing this to our attention. It will be fixed in the next release.

**Comment by sarahjeeeze** [comment]
Hi ,this should be fixed now
