### ISSUE TITLE
sequence alignment with "full reference QC"?

### ISSUE THREAD

**Issue by ChristopherRichie** [epi2me-labs/wf-clone-validation#53]
### Ask away!

When i run v1.3.1 without providing a reference, I see a "multiple sequence alignment" (MSA) even if there is only one plasmid in the "group".

When i run v1.3.1 and provide a full reference (or an insert reference), I get "full reference QC" (or "Insert variants") that indicates Indels and SNPs were found, and a BCF file.

is it possible to specify a pair-wise alignment  (final.fasta vs full_reference/insert_reference) as an output in the report?  The BCF file is not as immediately useful for my small plasmids, where i just want to know if the gene of interest has a mutation or if there is a deletion in my plasmid.

thanks

**Comment by sarahjeeeze** [comment]
Hi, thanks for the feedback,

For the first one - we will update this so it doesn't output single sequence MSA's, good point.
For the second one - yes, I think a pairwise alignment would be best. We currently are outputting an aligned BAM and in the future hope to display this in the IGV embedded with the application - are you running it in the app? Or would it be useful to have this as a section in the report?

**Comment by sarahjeeeze** [comment]
Closing for now but we have opened tickets internally to look in to potentially adding these things in future, but no timeline currently.
