### ISSUE TITLE
Erroneous sequence reported in insert fasta file

### ISSUE THREAD

**Issue by Nifaste** [epi2me-labs/wf-clone-validation#55]
### Ask away!

I have observed an error with the sequences of the inserts in the FASTA format: {{ alias }}.insert.fasta. I investigated the issue and it appears to originate from the following code in find_insert.py:

`rev_comp = reverse_complement(whole_seq)
strand_seq = {'-': rev_comp, '+': whole_seq}
parse_seq = strand_seq[str(df['strand'][0])]
final_seq = parse_seq[df['start'][0]::] + parse_seq[:df['end'][0]:]
df['sequence'][0] = final_seq`

The start and stop coordinates are not being adjusted when taking the reverse complement of the sequence.

![mapping_inserts_to_ref](https://github.com/user-attachments/assets/874cea4b-bb19-44a7-96f2-95546aec274a)

I fixed the issue with an update of the code

`insert_seq=whole_seq[df['start'][0]::] + whole_seq[:df['end'][0]:]
rev_comp = reverse_complement(insert_seq)
strand_seq = {'-': rev_comp, '+': insert_seq}
final_seq = strand_seq[str(df['strand'][0])]`

Has anyone else experienced this? Is my bug fix correct?

**Comment by sarahjeeeze** [comment]
Hi, thanks for reporting this. We will investigate and amend if required and let you know once implemented.

**Comment by sarahjeeeze** [comment]
Hi, After some investigation I see seqkit amplicon which we use for getting this sequence changed (fixed) the way it reported start and end sequences in the bed file from 2.4.0 which has resulted in this bug in the workflow. It previously did output the reverse complement start and end points. see - https://github.com/shenwei356/seqkit/issues/367. We will ammend. Thanks again for drawing our attention to this.

**Comment by sarahjeeeze** [comment]
Hey, although i can see what causes the error and will fix I am struggling to recreate the error within the workflow because for my datasets NaN is never reached as seqkit returns the sequence each time. If possible could you share any data such as your assembly and primers?

**Comment by sarahjeeeze** [comment]
Hi, we have now released the fix for this in the latest release.

**Comment by sarahjeeeze** [comment]
Closing as this is now fixed, let us know if you have further troubles
