### ISSUE TITLE
Is there a user-friendly way to inactivate plasmid annotation when using the workflow?

### ISSUE THREAD

**Issue by r-ovo-hm** [epi2me-labs/wf-clone-validation#58]
### Ask away!

My lab runs this workflow using the epi2me desktop application. 
the plasmid annotation feature is very useful, however is tends to be a bit too efficient, which raises sequence confidentiality concerns on our end.
is there a way to toggle off the annotation step without compromising the rest of the workflow? (either directly, or via a workaround?) thanks!

**Comment by sarahjeeeze** [comment]
Sorry for the late response - do you just not want it showing up in the report or you don't want it to run the annotation at all? Would you be happy to edit the code? If so I could let you know what to remove if not then we could potentially add a parameter to the workflow to toggle this.

**Comment by r-ovo-hm** [comment]
Would I be able to edit the code, then run the edited workflow on the desktop app? 
Not everyone in my team is proficient with working with command lines, so the ability to use the app is a requirement in our case. 
In our case I think turning off the annotation would be the better option, to avoid the use of unnecessary resources since we would not be using the annotation features at all.

**Comment by angelovangel** [comment]
I upvote this request! pLannotate is often the reason for crashing the pipeline, so it would be nice to have a parameter to skip it.

**Comment by sarahjeeeze** [comment]
We are very much considering incorporating this in a future release in some form, but can't give a timeline yet.
