### ISSUE TITLE
need help with 'pipeline:assembleCore'

### ISSUE THREAD

**Issue by Suchi-alt** [epi2me-labs/wf-clone-validation#59]
### Ask away!

I'm currently trying to run the wf-clone-validation workflow from the epi2me-labs repository using my FASTQ files. I have configured the workflow to use Flye as the assembly tool, but I'm encountering an error during the assembleCore process."[fc/61b5be] NOTE: Process `pipeline:assembleCore (1)` terminated with an error exit status (1) -- Execution is retried (1)"

**Comment by cjw85** [comment]
Please reopen your issue using the bug report template and provide the requested information.
