### ISSUE TITLE
Incompatibility with certain non-alphanumeric characters will break workflow

### ISSUE THREAD

**Issue by markb729** [epi2me-labs/wf-clone-validation#8]
### What happened?

When using a custom sample sheet, inclusion of certain non-alphanumeric characters will cause the pLannotate and report portions of the workflow to fail (e.g. a period "."). This looks to occur when the json.load function generates a dictionary automatically. Sample names that contain non-alphanumeric characters probably get filtered somewhere upstream, but the key is absent none-the-less and thus generates an error.

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - Execution Profile

Docker

### Workflow Version

d85691ac64

### Relevant log output

```shell
Traceback (most recent call last):
    File "/home/.nextflow/assets/epi2me-labs/wf-clone-validation/bin/report.py", line 308, in <module>
      main()
    File "/home/.nextflow/assets/epi2me-labs/wf-clone-validation/bin/report.py", line 246, in main
      tup_dic = plannotate[item]
  KeyError: 'pL2029.1'
```

**Comment by sarahjeeeze** [comment]
Thanks for pointing this out, I will look in to this and get back to you.

**Comment by sarahjeeeze** [comment]
This was fixed in a more recent version of the workflow, Closing through lack of response from original poster.
